import { createHash } from "crypto";
import { mkdir, readFile, writeFile } from "fs/promises";
import path from "path";

const root = () => path.resolve(process.env.STORAGE_DIR || "./storage", "files");

/** Stores the original bytes under a content-hash name. Files are never modified afterwards. */
export async function saveOriginal(bytes: Buffer, ext: string) {
  const sha256 = createHash("sha256").update(bytes).digest("hex");
  const storedName = `${sha256}${ext}`;
  await mkdir(root(), { recursive: true });
  await writeFile(path.join(root(), storedName), bytes);
  return { sha256, storedName };
}

export function readOriginal(storedName: string) {
  // storedName is generated by saveOriginal; reject anything that could escape the folder.
  if (!/^[a-f0-9]{64}\.[a-z]+$/.test(storedName)) throw new Error("Invalid stored file name");
  return readFile(path.join(root(), storedName));
}
